name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
#      - name: Run lint
#        run: ./gradlew :app:lintDebug
#      - run: npm ci
      - run: npm install glob
      - uses: actions/github-script@v6
        with:
          script: |
            const {globo} = require('glob')
            const xmlFiles = await globo('${github.workspace}/**/*.xml')
            const script = require('.github/workflows/lint_report.js')
            await script({github, context, xmlFiles})